services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev123
      POSTGRES_DB: cadastro_desenvolvedores
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  db_test:
    image: postgres:15-alpine
    container_name: postgres_db_test
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev123
      POSTGRES_DB: cadastro_desenvolvedores_test
    ports:
      - "6432:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data    

volumes:
  pgdata:
  pgdata_test:
